version: '2'
services:
  admin:
    image: rhchain
    ports:
      - "30303:30303"
      - "3000:3000"
      - "3001:3001"
  user1:
    image: rhchain-beta
    ports:
      - "30304:30303"
      - "3002:3000"
      - "3003:3001"
    environment:
      - BOOTNODE="127.0.0.1"
    links:
      - admin:admin 
  user2:
    image: rhchain-beta
    ports:
      - "30305:30303"
      - "3004:3000"
      - "3005:3001"
    environment:
      - BOOTNODE="127.0.0.1"
    links:
      - admin:admin 
