#!/bin/bash

WORK_DIR=$(pwd)
HOME=$(dirname $WORK_DIR)

SOLC=$HOME/cmd/bin/solc
GETH=$HOME/cmd/bin/geth

GETH_DATA_PATH=$HOME/geth
CONTRACT_JS=$GETH_DATA_PATH/contract.js
TMP_INIT_LOG=$GETH_DATA_PATH/init.tmp.log
NODE_DATA_PATH=$HOME/node
ETHEREUM_CONFIG_FILE_PATH=$NODE_DATA_PATH/ethereum.json

NODE_BACK_PORT=8000
NETWORK_ID=100
GETH_TCP_PORT=30303
RPC_ADDRESS=0.0.0.0
RPC_PORT=3001

